services:
  # Redis service for Channels and Celery
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL service (optional - for local development)
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: guitara_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Django application with enhanced WebSocket support
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Django settings
      - DEBUG=${DEBUG:-True}
      - DJANGO_SETTINGS_MODULE=guitara.settings_docker
      # Database settings
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME:-guitara_db}
      - SUPABASE_DB_USER=${SUPABASE_DB_USER:-postgres}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD:-postgres}
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST:-postgres}
      - SUPABASE_DB_PORT=${SUPABASE_DB_PORT:-5432}
      # Redis settings - Fixed environment variable format
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
      - CELERY_BROKER_URL=redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
      # Auto-create superuser
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD:-admin123}
      # Security
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,0.0.0.0}
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
      - ./logs:/app/logs
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  # Celery Worker for background tasks
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-True}
      - DJANGO_SETTINGS_MODULE=guitara.settings_docker
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME:-guitara_db}
      - SUPABASE_DB_USER=${SUPABASE_DB_USER:-postgres}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD:-postgres}
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST:-postgres}
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
      - CELERY_BROKER_URL=redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
    volumes:
      - media_volume:/app/media
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        /app/wait-for-services.sh &&
        cd /app/guitara &&
        celery -A guitara worker --loglevel=info --concurrency=2
      "

  # Celery Beat for periodic tasks
  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEBUG=${DEBUG:-True}
      - DJANGO_SETTINGS_MODULE=guitara.settings_docker
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME:-guitara_db}
      - SUPABASE_DB_USER=${SUPABASE_DB_USER:-postgres}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD:-postgres}
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST:-postgres}
      - REDIS_URL=redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
      - CELERY_BROKER_URL=redis://default:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-this-in-production}
    volumes:
      - media_volume:/app/media
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    command: >
      sh -c "
        /app/wait-for-services.sh &&
        cd /app/guitara &&
        celery -A guitara beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "

volumes:
  redis_data:
  postgres_data:
  media_volume:
  static_volume:

networks:
  default:
    name: guitara_network