@echo off
echo Restarting Django backend with Redis fallback fixes...
cd /d "c:\Users\USer\Downloads\Guitara-Scheduling-System\guitara"
echo Testing Django configuration...
python manage.py check
echo Starting Django server...
python manage.py runserver
