# Generated by Django 5.1.4 on 2025-06-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_available_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when driver became available for FIFO assignment', null=True),
        ),
    ]
