# Generated by Django 4.2.x on 2025-06-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # CustomUser Model Performance Indexes
        migrations.RunSQL(
            sql=[
                # Driver assignment optimization
                "CREATE INDEX idx_users_driver_available_fifo ON core_customuser(role, is_active, last_available_at) WHERE role = 'driver' AND is_active = true;",
                # Role-based queries
                "CREATE INDEX idx_users_role_active ON core_customuser(role, is_active);",
                "CREATE INDEX idx_users_therapist_active ON core_customuser(role, is_active, specialization) WHERE role = 'therapist' AND is_active = true;",
                "CREATE INDEX idx_users_driver_active ON core_customuser(role, is_active, motorcycle_plate) WHERE role = 'driver' AND is_active = true;",
                # Authentication and security
                "CREATE INDEX idx_users_email_verified ON core_customuser(email, email_verified);",
                "CREATE INDEX idx_users_failed_attempts ON core_customuser(failed_login_attempts, locked_until) WHERE failed_login_attempts > 0;",
                "CREATE INDEX idx_users_two_factor ON core_customuser(two_factor_enabled, email_verified) WHERE two_factor_enabled = true;",
                # User lookup optimization
                "CREATE INDEX idx_users_username_active ON core_customuser(username, is_active);",
                "CREATE INDEX idx_users_email_active ON core_customuser(email, is_active);",
                # Profile photo cache busting
                "CREATE INDEX idx_users_profile_photo ON core_customuser(profile_photo_url) WHERE profile_photo_url IS NOT NULL;",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_users_driver_available_fifo;",
                "DROP INDEX IF EXISTS idx_users_role_active;",
                "DROP INDEX IF EXISTS idx_users_therapist_active;",
                "DROP INDEX IF EXISTS idx_users_driver_active;",
                "DROP INDEX IF EXISTS idx_users_email_verified;",
                "DROP INDEX IF EXISTS idx_users_failed_attempts;",
                "DROP INDEX IF EXISTS idx_users_two_factor;",
                "DROP INDEX IF EXISTS idx_users_username_active;",
                "DROP INDEX IF EXISTS idx_users_email_active;",
                "DROP INDEX IF EXISTS idx_users_profile_photo;",
            ],
        ),
    ]
