# Generated by Django 5.1.4 on 2025-06-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_last_available_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_photo_url',
            field=models.URLField(blank=True, help_text='URL to profile photo stored in Supabase Storage', max_length=500, null=True),
        ),
    ]
