# Generated by Django 5.1.4 on 2025-06-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_performance_indexes'),
        ('core', '0003_customuser_profile_photo_url'),
    ]

    operations = [
    ]
