# Generated by Django 5.1.4 on 2025-07-09 08:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250619_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('authentication', 'Authentication'), ('appointment', 'Appointment'), ('payment', 'Payment'), ('data', 'Data'), ('system', 'System'), ('inventory', 'Inventory')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_systemlog',
                'ordering': ['-timestamp'],
                'managed': True,
            },
        ),
    ]
