# Generated by Django 5.1.4 on 2025-06-02 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Service', max_length=100)),
                ('description', models.CharField(default='Service description', max_length=255)),
                ('duration', models.DurationField(default=60, help_text='Duration in minutes')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('oil', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed Material', max_length=100)),
                ('description', models.CharField(default='Material for massage service', max_length=255)),
                ('category', models.CharField(choices=[('Massage Oil', 'Massage Oil'), ('Massage Supplies', 'Massage Supplies'), ('Hygiene Supplies', 'Hygiene Supplies'), ('Ventosa Supplies', 'Ventosa Supplies'), ('Equipment', 'Equipment'), ('Other', 'Other')], default='Other', max_length=50)),
                ('unit_of_measure', models.CharField(choices=[('Bottle', 'Bottle'), ('Tub', 'Tub'), ('Spray Bottle', 'Spray Bottle'), ('Unit', 'Unit'), ('Set', 'Set'), ('Pack', 'Pack'), ('Other', 'Other')], default='Unit', max_length=50)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('auto_deduct', models.BooleanField(default=False, help_text='Automatically deduct from inventory when booking is created')),
                ('reusable', models.BooleanField(default=False, help_text='Whether this material can be reused')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='registration.service')),
            ],
        ),
    ]
