# Generated by Django 5.1.4 on 2025-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='massage_pressure',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='username',
        ),
        migrations.AddField(
            model_name='therapist',
            name='availability',
            field=models.CharField(default='Available', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='contact_number',
            field=models.CharField(default='000-000-0000', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='first_name',
            field=models.CharField(default='Jay', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='last_name',
            field=models.CharField(default='Tralalelo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='pressure_preference',
            field=models.CharField(default='Hard', max_length=100),
            preserve_default=False,
        ),
    ]
