# Generated by Django 5.1.4 on 2025-06-01 22:24

from django.db import migrations
from datetime import timedelta


def create_initial_services(apps, schema_editor):
    
class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_services, migrations.RunPython.noop),
    ]
    Service = apps.get_model('registration', 'Service')
    
    # Create predefined services with exact IDs to match frontend expectations
    services_data = [
        {            'id': 1,
            'name': 'Shiatsu Massage',
            'description': 'A Japanese technique involving pressure points.',
            'duration': timedelta(minutes=60),  # 1 hour
            'price': 500.00,
            'is_active': True,
        },
        {            'id': 2,
            'name': 'Combi Massage',
            'description': 'A combination of multiple massage techniques.',
            'duration': timedelta(minutes=60),
            'price': 550.00,
            'is_active': True,
        },
        {
            'id': 3,
            'name': 'Dry Massage',
            'description': 'Performed without oils or lotions.',
            'duration': 60,
            'price': 450.00,
            'is_active': True,
        },
        {
            'id': 4,
            'name': 'Foot Massage',
            'description': 'Focused on the feet and lower legs.',
            'duration': 60,
            'price': 400.00,
            'is_active': True,
        },
        {
            'id': 5,
            'name': 'Hot Stone Service',
            'description': 'Uses heated stones for deep muscle relaxation.',
            'duration': 90,  # 1.5 hours
            'price': 650.00,
            'is_active': True,
        },
        {
            'id': 6,
            'name': 'Ventosa',
            'description': 'Traditional cupping therapy to relieve muscle tension.',
            'duration': 45,  # 45 minutes
            'price': 450.00,
            'is_active': True,
        },
        {
            'id': 7,
            'name': 'Hand Massage',
            'description': 'Focused on hands and arms.',
            'duration': 45,  # 45 minutes
            'price': 350.00,
            'is_active': True,
        },
    ]
    
    # Delete any existing services to ensure clean slate
    Service.objects.all().delete()
    
    # Create new services with specified IDs
    for service_data in services_data:        Service.objects.create(**service_data)
        print(f"Created service: {service_data['name']} (ID: {service_data['id']})")
