# Generated by Django 5.1.4 on 2025-06-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_driver_email_driver_first_name_driver_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
    ]
