# Generated by Django 5.1.4 on 2025-05-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_remove_therapist_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='availability',
            field=models.CharField(blank=True, default='Available', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='contact_number',
            field=models.CharField(blank=True, default='N/A', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='first_name',
            field=models.CharField(blank=True, default='First Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='last_name',
            field=models.CharField(blank=True, default='Last Name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='pressure_preference',
            field=models.CharField(blank=True, default='Standard', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='specialization',
            field=models.CharField(blank=True, default='Specialization', max_length=100, null=True),
        ),
    ]
