# Generated by Django 5.1.4 on 2025-05-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_therapist_availability_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapist',
            old_name='pressure_preference',
            new_name='massage_pressure',
        ),
        migrations.RenameField(
            model_name='therapist',
            old_name='contact_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='availability',
        ),
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='First Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operator',
            name='first_name',
            field=models.CharField(default='First Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operator',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='email',
            field=models.EmailField(default='Email', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='therapist',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='username',
            field=models.CharField(default='Username', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='motorcycle_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(blank=True, default='N/A', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='phone_number',
            field=models.CharField(blank=True, default='N/A', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='first_name',
            field=models.CharField(default='First Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapist',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='therapist',
            name='specialization',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
