# Generated by Django 5.1.4 on 2025-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_add_performance_indexes'),
        ('registration', '0003_alter_service_duration'),
    ]

    operations = [
    ]
