# Generated by Django 5.1.4 on 2025-06-26 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryitem_size_per_unit'),
        ('registration', '0004_merge_20250619_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='stock_quantity',
        ),
        migrations.AlterModelTable(
            name='material',
            table='registration_material_legacy',
        ),
        migrations.CreateModel(
            name='RegistrationMaterial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_of_measure', models.CharField(blank=True, max_length=50, null=True)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('auto_deduct', models.BooleanField(default=False)),
                ('reusable', models.BooleanField(default=False)),
                ('inventory_item', models.ForeignKey(blank=True, db_column='inventory_item_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventoryitem')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='registration.service')),
            ],
            options={
                'db_table': 'registration_material',
            },
        ),
    ]
