# Generated by Django 5.1.4 on 2025-05-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_remove_driver_motorcycle_plate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='username',
        ),
        migrations.RemoveField(
            model_name='material',
            name='description',
        ),
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='email',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='username',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='massage_pressure',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='username',
        ),
    ]
