# Generated by Django 5.1.4 on 2025-05-31 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial_services'),
        ('registration', '0006_remove_driver_email_remove_driver_first_name_and_more'),
    ]

    operations = [
    ]
