# Generated by Django 5.1.4 on 2025-05-31 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_add_initial_services'),
        ('registration', '0009_service_is_active_create_initial_services'),
    ]

    operations = [
    ]
