version: "3.8"

services:
  # Redis service for Channels and Celery
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Django application with ASGI (Channels support)
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Production settings
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=guitara.settings_production
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      # Database (Supabase)
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME}
      - SUPABASE_DB_USER=${SUPABASE_DB_USER}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST}
      # Redis for Channels and Celery
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      # Email settings
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      # Security
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    depends_on:
      redis:
        condition: service_healthy
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        daphne -b 0.0.0.0 -p 8000 guitara.asgi:application
      "

  # Celery Worker for background tasks
  celery:
    build: .
    restart: unless-stopped
    environment:
      # Production settings
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=guitara.settings_production
      # Database (Supabase)
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME}
      - SUPABASE_DB_USER=${SUPABASE_DB_USER}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST}
      # Redis for Celery
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      # Email settings
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      # Security
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A guitara worker --loglevel=info --concurrency=2 --max-tasks-per-child=1000

  # Celery Beat for periodic tasks
  celery-beat:
    build: .
    restart: unless-stopped
    environment:
      # Production settings
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=guitara.settings_production
      # Database (Supabase)
      - SUPABASE_DB_NAME=${SUPABASE_DB_NAME}
      - SUPABASE_DB_USER=${SUPABASE_DB_USER}
      - SUPABASE_DB_PASSWORD=${SUPABASE_DB_PASSWORD}
      - SUPABASE_DB_HOST=${SUPABASE_DB_HOST}
      # Redis for Celery
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      # Email settings
      - EMAIL_HOST_USER=${EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      # Security
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A guitara beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler

volumes:
  redis_data:
  media_volume:
  static_volume:

networks:
  default:
    name: guitara_network
