# Generated by Django 5.1.4 on 2025-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_usagelog_notes"),
        ("inventory", "0003_usagelog_notes"),
    ]

    operations = []
