# Generated by Django 5.1.4 on 2025-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_inventoryitem_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='size_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Size per unit in ml or g, if applicable', max_digits=10, null=True),
        ),
    ]
