# Generated by Django 5.1.4 on 2025-07-06 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_simplify_inventory_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelog',
            name='action_type',
            field=models.CharField(choices=[('restock', 'Restock'), ('usage', 'Usage'), ('empty', 'Marked as Empty'), ('returned', 'Returned to Stock')], default='usage', max_length=20),
        ),
    ]
