# Generated by Django 4.2.x on 2025-06-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        # TwoFactorCode Model Performance Indexes
        migrations.RunSQL(
            sql=[
                # 2FA code lookups
                "CREATE INDEX idx_2fa_user_code ON authentication_twofactorcode(user_id, code, is_used);",
                "CREATE INDEX idx_2fa_code_expires ON authentication_twofactorcode(code, expires_at, is_used) WHERE is_used = false;",
                "CREATE INDEX idx_2fa_user_active ON authentication_twofactorcode(user_id, expires_at, is_used) WHERE is_used = false;",
                # Cleanup expired codes - Fixed: Removed NOW() function
                "CREATE INDEX idx_2fa_expired_cleanup ON authentication_twofactorcode(expires_at, is_used);",
                # User's active codes
                "CREATE INDEX idx_2fa_user_valid_codes ON authentication_twofactorcode(user_id, created_at, expires_at) WHERE is_used = false;",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_2fa_user_code;",
                "DROP INDEX IF EXISTS idx_2fa_code_expires;",
                "DROP INDEX IF EXISTS idx_2fa_user_active;",
                "DROP INDEX IF EXISTS idx_2fa_expired_cleanup;",
                "DROP INDEX IF EXISTS idx_2fa_user_valid_codes;",
            ],
        ),
        # PasswordResetCode Model Performance Indexes
        migrations.RunSQL(
            sql=[
                # Password reset code lookups
                "CREATE INDEX idx_password_reset_user_code ON authentication_passwordresetcode(user_id, code, is_used);",
                "CREATE INDEX idx_password_reset_code_expires ON authentication_passwordresetcode(code, expires_at, is_used) WHERE is_used = false;",
                "CREATE INDEX idx_password_reset_user_active ON authentication_passwordresetcode(user_id, expires_at, is_used) WHERE is_used = false;",
                # Cleanup expired codes - Fixed: Removed NOW() function
                "CREATE INDEX idx_password_reset_expired_cleanup ON authentication_passwordresetcode(expires_at, is_used);",
                # User's active reset codes
                "CREATE INDEX idx_password_reset_user_valid_codes ON authentication_passwordresetcode(user_id, created_at, expires_at) WHERE is_used = false;",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_password_reset_user_code;",
                "DROP INDEX IF EXISTS idx_password_reset_code_expires;",
                "DROP INDEX IF EXISTS idx_password_reset_user_active;",
                "DROP INDEX IF EXISTS idx_password_reset_expired_cleanup;",
                "DROP INDEX IF EXISTS idx_password_reset_user_valid_codes;",
            ],
        ),
    ]
