# Generated by Django 5.1.4 on 2025-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_performance_indexes'),
        ('authentication', '0002_passwordresetcode'),
    ]

    operations = [
    ]
