# Generated by Django 5.1.4 on 2025-06-04 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='auto_cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the appointment was auto-cancelled due to timeout', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='When the appointment was rejected', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejected_by',
            field=models.ForeignKey(blank=True, help_text='User who rejected the appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection provided by therapist', null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='response_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for therapist to respond (30 minutes after creation)', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('auto_cancelled', 'Auto Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling.appointment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_created', 'Appointment Created'), ('appointment_updated', 'Appointment Updated'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled'), ('appointment_accepted', 'Appointment Accepted'), ('appointment_rejected', 'Appointment Rejected'), ('appointment_started', 'Appointment Started'), ('appointment_completed', 'Appointment Completed'), ('appointment_auto_cancelled', 'Appointment Auto Cancelled'), ('rejection_reviewed', 'Rejection Reviewed'), ('therapist_disabled', 'Therapist Disabled')], default='appointment_created', max_length=30),
        ),
        migrations.CreateModel(
            name='AppointmentRejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason', models.TextField(help_text='Reason provided by therapist for rejecting')),
                ('rejected_at', models.DateTimeField(auto_now_add=True)),
                ('operator_response', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Reason Accepted'), ('denied', 'Reason Denied')], default='pending', max_length=20)),
                ('operator_response_reason', models.TextField(blank=True, help_text="Operator's reason for accepting/denying the rejection", null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_details', to='scheduling.appointment')),
                ('rejected_by', models.ForeignKey(help_text='Therapist who rejected the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='rejections_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Operator who reviewed the rejection', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='rejection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling.appointmentrejection'),
        ),
    ]
