# Generated by Django 5.1.4 on 2025-05-15 14:58

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


def set_default_appointment(apps, schema_editor):
    Notification = apps.get_model('scheduling', 'Notification')
    Appointment = apps.get_model('scheduling', 'Appointment')
    Client = apps.get_model('scheduling', 'Client')
    Service = apps.get_model('registration', 'Service')

    # Find a default appointment to use. Create one if none exists.
    default_appointment = Appointment.objects.first()

    if not default_appointment:
        # First ensure we have a client
        default_client = Client.objects.first()
        if not default_client:
            default_client = Client.objects.create(
                first_name="Default",
                last_name="Client",
                phone_number="0000000000",
                address="Default Address"
            )
        
        # Create default appointment without the 'services' parameter since it's a M2M field
        default_appointment = Appointment.objects.create(
            client=default_client,
            date=timezone.now().date(),
            start_time=timezone.now().time(),
            end_time=(timezone.now() + timezone.timedelta(hours=1)).time(),
            therapist=None,
            driver=None,
            operator=None,
            location="Default Location",
            status="pending",
            payment_status="unpaid",
            payment_amount=0
        )
        
        # Add a service to the M2M field after creation if any exists
        default_service = Service.objects.first()
        if default_service:
            default_appointment.services.add(default_service)

    # Update all notifications with NULL appointments
    for notification in Notification.objects.filter(appointment__isnull=True):
        notification.appointment = default_appointment
        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='type',
        ),
        migrations.AddField(
            model_name='appointment',
            name='required_materials',
            field=models.TextField(blank=True, help_text='Materials needed for this appointment', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('appointment_created', 'Appointment Created'), ('appointment_updated', 'Appointment Updated'), ('appointment_reminder', 'Appointment Reminder'), ('appointment_cancelled', 'Appointment Cancelled')], default='appointment_created', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduling.appointment'),
        ),
        migrations.RunPython(set_default_appointment, migrations.RunPython.noop),
    ]
