# Generated by Django 5.1.4 on 2025-06-08 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_appointment_driver_accepted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='therapists',
            field=models.ManyToManyField(blank=True, help_text='Multiple therapists for group appointments', limit_choices_to={'role': 'therapist'}, related_name='multi_therapist_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
