# Generated by Django 5.1.4 on 2025-06-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_add_pickup_workflow_fields'),
        ('scheduling', '0004_appointment_therapists'),
    ]

    operations = [
    ]
