# Generated by Django 5.1.4 on 2025-06-08 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_enhanced_service_flow'),
        ('scheduling', '0005_merge_20250608_2221'),
    ]

    operations = [
    ]
