# Generated by Django 5.1.4 on 2025-06-09 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_merge_20250609_0041'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='When the appointment was officially started by operator', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('therapist_confirm', 'Therapist Confirm'), ('driver_confirm', 'Driver Confirm'), ('driver_confirmed', 'Driver Confirmed'), ('in_progress', 'In Progress'), ('journey', 'Journey'), ('arrived', 'Arrived'), ('dropped_off', 'Dropped Off'), ('session_in_progress', 'Session In Progress'), ('awaiting_payment', 'Awaiting Payment'), ('completed', 'Completed'), ('pickup_requested', 'Pickup Requested'), ('driver_assigned_pickup', 'Driver Assigned for Pickup'), ('return_journey', 'Return Journey'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('auto_cancelled', 'Auto Cancelled'), ('confirmed', 'Confirmed'), ('driving_to_location', 'Driver En Route'), ('at_location', 'Driver at Location'), ('therapist_dropped_off', 'Therapist Dropped Off'), ('transport_completed', 'Transport Completed'), ('picking_up_therapists', 'Picking Up Therapists'), ('transporting_group', 'Transporting Group'), ('driver_assigned', 'Driver Assigned')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='TherapistConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapist_confirmations', to='scheduling.appointment')),
                ('therapist', models.ForeignKey(limit_choices_to={'role': 'therapist'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('appointment', 'therapist')},
            },
        ),
    ]
