# Generated by Django 5.1.4 on 2025-06-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0009_add_pickup_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='return_journey_completed_at',
            field=models.DateTimeField(blank=True, help_text='When the return journey (therapist pickup) was completed', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('therapist_confirmed', 'Therapist Confirmed'), ('driver_confirmed', 'Driver Confirmed'), ('in_progress', 'In Progress'), ('journey', 'Journey'), ('arrived', 'Arrived'), ('dropped_off', 'Dropped Off'), ('session_in_progress', 'Session In Progress'), ('awaiting_payment', 'Awaiting Payment'), ('completed', 'Completed'), ('pickup_requested', 'Pickup Requested'), ('driver_assigned_pickup', 'Driver Assigned for Pickup'), ('return_journey', 'Return Journey'), ('transport_completed', 'Transport Completed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('auto_cancelled', 'Auto Cancelled'), ('therapist_confirm', 'Therapist Confirm'), ('driver_confirm', 'Driver Confirm'), ('confirmed', 'Confirmed'), ('driving_to_location', 'Driver En Route'), ('at_location', 'Driver at Location'), ('therapist_dropped_off', 'Therapist Dropped Off'), ('transport_completed', 'Transport Completed'), ('picking_up_therapists', 'Picking Up Therapists'), ('transporting_group', 'Transporting Group'), ('driver_assigned', 'Driver Assigned')], default='pending', max_length=30),
        ),
    ]
