# Generated by adding missing payment verification fields

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling", "0012_alter_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("gcash", "GCash"),
                    ("bank_transfer", "Bank Transfer"),
                    ("credit_card", "Credit Card"),
                ],
                default="cash",
                help_text="Method used for payment",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When payment was verified by operator",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_verified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Operator who verified the payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_payments",
                to="core.customuser",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="payment_notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes about the payment",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="receipt_hash",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash of uploaded payment receipt",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="receipt_url",
            field=models.URLField(
                blank=True,
                help_text="URL to uploaded payment receipt",
                null=True,
            ),
        ),
    ]
