# Generated by Django 5.1.4 on 2025-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_add_performance_indexes'),
        ('scheduling', '0012_alter_appointment_status'),
    ]

    operations = [
    ]
