# Generated by Performance Optimization on 2025-06-20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduling", "0013_merge_20250619_2037"),
        ("core", "0004_merge_20250619_2036"),
        ("knox", "0008_remove_authtoken_salt"),
    ]

    operations = [
        # Critical appointment indexes for ultra-fast queries
        migrations.RunSQL(
            [
                # Compound index for status + date queries (most common operator dashboard query)
                "CREATE INDEX IF NOT EXISTS idx_appointments_status_date ON scheduling_appointment(status, date);",
                # Index for date range queries with created_at
                "CREATE INDEX IF NOT EXISTS idx_appointments_date_created ON scheduling_appointment(date, created_at);",
                # Index for therapist-related queries (therapist dashboard)
                "CREATE INDEX IF NOT EXISTS idx_appointments_therapist_status ON scheduling_appointment(therapist_id, status) WHERE therapist_id IS NOT NULL;",
                # Index for driver-related queries (driver dashboard)
                "CREATE INDEX IF NOT EXISTS idx_appointments_driver_status ON scheduling_appointment(driver_id, status) WHERE driver_id IS NOT NULL;",
                # Index for client-related queries
                "CREATE INDEX IF NOT EXISTS idx_appointments_client_date ON scheduling_appointment(client_id, date);",
                # Critical index for response deadline queries (timeout monitoring)
                "CREATE INDEX IF NOT EXISTS idx_appointments_response_deadline ON scheduling_appointment(response_deadline) WHERE response_deadline IS NOT NULL;",
                # Index for payment status queries
                "CREATE INDEX IF NOT EXISTS idx_appointments_payment_status ON scheduling_appointment(payment_status, status);",
                # Knox authentication optimization - CRITICAL for 32s query fix
                "CREATE INDEX IF NOT EXISTS idx_knox_token_digest_user ON knox_authtoken(digest, user_id);",
                # User lookup optimization - prevents repeated user queries
                "CREATE INDEX IF NOT EXISTS idx_customuser_active ON core_customuser(id, is_active) WHERE is_active = true;",
                # Services relationship optimization
                "CREATE INDEX IF NOT EXISTS idx_appointment_services_appointment ON scheduling_appointment_services(appointment_id);",
                "CREATE INDEX IF NOT EXISTS idx_appointment_services_service ON scheduling_appointment_services(service_id);",
                # Notification optimization for operator dashboard
                "CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON scheduling_notification(user_id, is_read);",
                # Availability optimization
                "CREATE INDEX IF NOT EXISTS idx_availability_user_date ON scheduling_availability(user_id, date);",
                # Client optimization
                "CREATE INDEX IF NOT EXISTS idx_client_name ON scheduling_client(first_name, last_name);",
            ],
            reverse_sql=[
                "DROP INDEX IF EXISTS idx_appointments_status_date;",
                "DROP INDEX IF EXISTS idx_appointments_date_created;",
                "DROP INDEX IF EXISTS idx_appointments_therapist_status;",
                "DROP INDEX IF EXISTS idx_appointments_driver_status;",
                "DROP INDEX IF EXISTS idx_appointments_client_date;",
                "DROP INDEX IF EXISTS idx_appointments_response_deadline;",
                "DROP INDEX IF EXISTS idx_appointments_payment_status;",
                "DROP INDEX IF EXISTS idx_knox_token_digest_user;",
                "DROP INDEX IF EXISTS idx_customuser_active;",
                "DROP INDEX IF EXISTS idx_appointment_services_appointment;",
                "DROP INDEX IF EXISTS idx_appointment_services_service;",
                "DROP INDEX IF EXISTS idx_notifications_user_read;",
                "DROP INDEX IF EXISTS idx_availability_user_date;",
                "DROP INDEX IF EXISTS idx_client_name;",
            ],
        ),
    ]
