# Generated by Django 5.1.4 on 2025-07-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0016_add_appointment_materials'),
        ('scheduling', '0016_fix_duplicate_payment_fields'),
    ]

    operations = [
    ]
