# Generated by Django 5.1.4 on 2025-07-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0018_alter_appointmentmaterial_quantity_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Additional appointment data such as service extensions', null=True),
        ),
    ]
