# Generated by Django 5.1.4 on 2025-05-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_rename_pressure_preference_therapist_massage_pressure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='motorcycle_plate',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='phone_number',
        ),
    ]
