# Generated by Django 5.1.4 on 2025-05-31 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_merge_20250531_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='auto_deduct',
            field=models.BooleanField(default=False, help_text='Automatically deduct from inventory when booking is created'),
        ),
        migrations.AddField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('Massage Oil', 'Massage Oil'), ('Massage Supplies', 'Massage Supplies'), ('Hygiene Supplies', 'Hygiene Supplies'), ('Ventosa Supplies', 'Ventosa Supplies'), ('Equipment', 'Equipment'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.CharField(default='Material for massage service', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default='Unnamed Material', max_length=100),
        ),
        migrations.AddField(
            model_name='material',
            name='reusable',
            field=models.BooleanField(default=False, help_text='Whether this material can be reused'),
        ),
        migrations.AddField(
            model_name='material',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='registration.service'),
        ),
        migrations.AddField(
            model_name='material',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='unit_of_measure',
            field=models.CharField(choices=[('Bottle', 'Bottle'), ('Tub', 'Tub'), ('Spray Bottle', 'Spray Bottle'), ('Unit', 'Unit'), ('Set', 'Set'), ('Pack', 'Pack'), ('Other', 'Other')], default='Unit', max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default='Service description', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='duration',
            field=models.IntegerField(default=60, help_text='Duration in minutes'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='New Service', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='oil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
